env:
  browser: true
  es6: true
extends:
  - prettier
  # - eslint:recommended
  # - plugin:import/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
  - import
rules:
  prettier/prettier: [error]
  "@typescript-eslint/no-unused-vars":
    [
      warn,
      {
        ignoreRestSiblings: true,
        vars: all,
        varsIgnorePattern: "^_$",
        args: none,
      },
    ]
  prefer-const: [warn, { destructuring: all }]
  guard-for-in: [error]
  "import/extensions": [error, ignorePackages]
  "import/no-extraneous-dependencies": [error]
